name: build

on:
  push:
    branches: [ master ]
    tags:     [ v* ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: login to ghcr
        id: docker_login
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5.5.0
        with:
          images: ghcr.io/semior001/gryper
          tags: |
            type=raw,value=latest
            type=semver,pattern=raw

      - name: build and push tagged docker image
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        id: docker_build
        uses: docker/build-push-action@v2
        env:
          GITHUB_TAG: ${{ github.ref }}
        with:
          push: true
          context: .
          tags: ${{ steps.meta.outputs.tags }}

      - name: cleanup old images
        if: ${{ github.ref == 'refs/heads/master' }}
        uses: actions/delete-package-versions@v4
        continue-on-error: true
        with:
          package-name: gryper
          package-type: container
          min-versions-to-keep: 3
          ignore-versions: "^(latest|v[0-9]\\.[0-9]\\.[0-9])$"